### PR TITLE
THEEDGE-2589 Added new status and retry popover on device details

### PR DESCRIPTION
**Pull request by de1987**
# Description

- Added new status and retry popover on device details.
- Added new props on the popover component to change the position.
- Refactored `getDevicesStatus` for reuse and maintainability.

Fixes # [(THEEDGE-2589)](https://issues.redhat.com/browse/THEEDGE-2589)

## Type of change

What is it?

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [ ] Tests update

# Checklist:

- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] I run `npm run lint:js:fix` to check that my code is properly formatted

### CODE REVIEW

**Comment by de1987** [comment]
Depends on https://github.com/RedHatInsights/edge-frontend/pull/533, need to wait until this PR is merged.

**Review by acosferreira — APPROVED** [review]
lgtm

**Comment by tpapaioa** [comment]
The breadcrumbs for the system details page are broken:

image

**Review by acruzgon — APPROVED** [review]
nice job!

**Pull request merged**
