### PR TITLE
Disable default columns

### PR DESCRIPTION
**Pull request by rvsia**
cc @karelhala

### CODE REVIEW

**Review by boaz0 — APPROVED** [review]

**Comment by boaz0** [comment]
@rvsia why did you close it?

**Comment by rvsia** [comment]
@boaz0 It has been opened for months now and `InventoryTable` code has been changed so this is not currently required when setting custom columns via Redux. And because it hasn't been merged yet, it probably causes no issues in this application.

**Comment by boaz0** [comment]
I am sorry it was opened too long. I didn't get my head around this. But soon I am taking care of adding the image status in the devices page. Do you mind if I re-open it for another month just in case it will be relevant?

And again. I am so sorry for my late response.

**Comment by boaz0** [comment]
@rvsia - you were right. It's no longer relevant. Thanks for your help with the inventory table though!
Again I am sorry for the long review process! Appreciate your help as always!!! :bow: :pray:

**Pull request closed without merging**
