### PR TITLE
Replace ImageISOURL to ImageBuildISOURL for isoURL to show actions

### PR DESCRIPTION
**Pull request by matoval**
Replace ImageISOURL to ImageBuildISOURL to show the download button for the images with an ISO URL

### CODE REVIEW

**Comment by omaciel** [comment]
Looks like an easy merge :)

**Comment by boaz0** [comment]
@matoval for some reason all your PRs are not executing Travis CI. Can you try to `git pull --rebase upstream HEAD`?

**Comment by matoval** [comment]
I tried the git command but it says everything is up to date. I tried creating a new PR maybe that'll work?

**Comment by boaz0** [comment]
closing in favor of https://github.com/RedHatInsights/edge-frontend/pull/99

**Pull request closed without merging**
