### PR TITLE
Update update image wizard

### PR DESCRIPTION
**Pull request by resoluteCoder**
Added update image wizard and supporting files. 

Things to note:
PR #98 adds actions to open wizard and sets up file. should be able to pull both without merge conflict.
Need some review on what API to call to update the image, UI should be all there.

### CODE REVIEW

**Comment by boaz0** [comment]
@resoluteCoder lets try this. I am assigning @matoval to review your code and you will review his PRs later.

**Review by matoval — APPROVED** [review]
Look's good! I tested this branch with [PR](https://github.com/RedHatInsights/edge-frontend/pull/98) and everything worked properly.

**Comment by boaz0** [comment]
@resoluteCoder please run `git --rebase upstream HEAD`

**Comment by boaz0** [comment]
https://github.com/RedHatInsights/edge-frontend/pull/100/files#diff-cfc089c2542316adf1010f38f95ecfc262d24a3a5f14dc077aa66dab763a28f1R44
Please update this accordingly. It needs to be `values.version + 1`.

In addition, did you manage to run this against Edge API?

**Review by boaz0 — COMMENTED** [review]
LGTM

**Pull request merged**
