### PR TITLE
THEEDGE-3290 - Match Kebab actions with Insights Kebab

### PR DESCRIPTION
**Pull request by acruzgon**
# Description

This PR is adding Edit and Delete options to the Inventory table kebab to match kebab in insights Inventory
Before:
image

After:
image

As well it's adding the config to run against any fed module.

Fixes # ([THEEDGE-3290](https://issues.redhat.com/browse/THEEDGE-3290))

## Type of change

What is it?

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [X] Documentation update
- [ ] Tests update

# Checklist:

- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [X] I run `npm run lint:js:fix` to check that my code is properly formatted

### CODE REVIEW

**Review by adeliaferreira — DISMISSED** [review]
lgtm

**Review by acosferreira — APPROVED** [review]
lgtm

**Comment by omaciel** [comment]
Question: do we need to do anything on our end to ensure that the Delete action does anything? What is the action performed when the user clicks the Delete button? Do we just delete it from the Inventory? Do we run `rhc disconnect` via a playbook? What are the expected behaviors for the user?

**Review by adeliaferreira — APPROVED** [review]
lgtm

**Comment by de1987** [comment]
> Question: do we need to do anything on our end to ensure that the Delete action does anything? What is the action performed when the user clicks the Delete button? Do we just delete it from the Inventory? Do we run `rhc disconnect` via a playbook? What are the expected behaviors for the user?

good point
@acruzgon I think you should take a look on this

**Comment by acruzgon** [comment]
> > Question: do we need to do anything on our end to ensure that the Delete action does anything? What is the action performed when the user clicks the Delete button? Do we just delete it from the Inventory? Do we run `rhc disconnect` via a playbook? What are the expected behaviors for the user?
> 
> good point @acruzgon I think you should take a look on this

that was already addressed offline in a slack thread but to keep track i'm adding it here as well -  the modal is informing the user that they need to manually unregister the system
image

**Review by de1987 — APPROVED** [review]

**Pull request merged**
