### PR TITLE
Fix vulnerability table

### PR DESCRIPTION
**Pull request by de1987**
# Description

Fix the vulnerability table by removing the advisory column

## Type of change

What is it?

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [ ] Tests update

### CODE REVIEW

**Review by acosferreira — APPROVED** [review]
lgtm

**Review by matoval — APPROVED** [review]

**Comment by de1987** [comment]
@mergifyio check

**Comment by de1987** [comment]
@mergifyio retest

**Comment by de1987** [comment]
@mergifyio /retest

**Comment by de1987** [comment]
@mergifyio refresh

**Comment by ezr-ondrej** [comment]
https://github.com/Mergifyio cancel

**Comment by ezr-ondrej** [comment]
@Mergifyio dequeue

**Comment by ezr-ondrej** [comment]
@mergifyio refresh

**Pull request merged**
