### PR TITLE
migrate to PF5 (HMS-4450)

### PR DESCRIPTION
**Pull request by amirfefer**
# Description
WIP

This PR migrate to PF5, but uses the deprecated PF4 for components.
This migration forces us to bump react to version 18.x, frontend-components, and react testing library, due to peer dependencies.

## Type of change

What is it?

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [ ] Tests update

### CODE REVIEW

**Comment by ezr-ondrej** [comment]
Looks like some nasty dependency error, let me know if I should help google solutions :)

**Comment by amirfefer** [comment]
#### Update on the Latest Test Commit

This service relies heavily on the snapshot testing mechanism, so extra caution is required during verification. I have carefully reviewed each snapshot that includes changes to PF4 styles. Additionally, I manually tested the main pages to ensure they are navigable and functioning as expected. I also verified that creating new images and updating them works as intended.

**Comment by InsightsDroid** [comment]
## :exclamation: Outdated dependencies error
* Installed version of react-router-dom (5.3.4) is older than required version (6.0.0)
* Installed version of @redhat-cloud-services/frontend-components-config (4.7.3) is older than required version (6.0.0)

**Review by ezr-ondrej — APPROVED** [review]
Amazing work! :orange_heart: Thank you @amirfefer!
Lets :shipit:

**Pull request merged**
