### PR TITLE
feat: create new federated module to expose ImageDeatilsCard

### PR DESCRIPTION
**Pull request by adeliaferreira**
…ed by Insights Inventory

# Description

As part of Edge feature parity initiative, this PR will create a federated module for ImageDetailsCard to be used by Insights inventory to show image details for devices (called by them as Inventory).

Fixes # THEEDGE-3359

## Type of change

What is it?

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [ ] Tests update

# Checklist:

- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [X] I run `npm run lint:js:fix` to check that my code is properly formatted

### CODE REVIEW

**Review by ldjebran — APPROVED** [review]
lgtm

**Review by mgold1234 — APPROVED** [review]
/lgtm

**Review by mgold1234 — APPROVED** [review]

**Review by mgold1234 — APPROVED** [review]
/lgtm

**Review by mgold1234 — APPROVED** [review]
/lgtm

**Review by mgold1234 — APPROVED** [review]

**Review by mgold1234 — CHANGES_REQUESTED** [review]
please

**Review by mgold1234 — APPROVED** [review]
/lgtm

**Comment by adeliaferreira** [comment]
michal approved but the merge bot don't merge.

**Pull request merged**
