### PR TITLE
Stop promoting code to BETA | STABLE environments

### PR DESCRIPTION
**Pull request by omaciel**
Stop promoting UI code to ${ENV}-beta or ${ENV}-stable

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # THEEDGE-3130

## Type of change

What is it?

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [ ] Tests update

# Checklist:

- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] I run `npm run lint:js:fix` to check that my code is properly formatted

### CODE REVIEW

**Comment by matoval** [comment]
@karelhala We would like to change our default stage environment to be stage-stable instead of stage-beta. We really don't need either stage-beta or prod-beta as we never use them as actual beta env. I'm not sure if it would be better for use to remove the beta env or keep beta and stable in sync at all times.

**Comment by karelhala** [comment]
@matoval you're better off by syncing beta and stable environments. If you were to skip pushing to beta altogether some integration teams might have harder times figuring out what's causing some errors.

**Review by karelhala — COMMENTED** [review]
This will not work properly as we are matching build branches as:
* https://github.com/RedHatInsights/edge-frontend-build/tree/ci-beta to console.stage.redhat.com/beta
* https://github.com/RedHatInsights/edge-frontend-build/tree/ci-stable to console.stage.redhat.com
* https://github.com/RedHatInsights/edge-frontend-build/tree/prod-beta to console.redhat.com/beta
* https://github.com/RedHatInsights/edge-frontend-build/tree/prod-stable to console.redhat.com

You might want to change this custom release script to:
```sh
#!/bin/bash
set -e
set -x

if [ "${TRAVIS_BRANCH}" = "master" ]
then
    for env in ci qa
    do
        echo "PUSHING ${env}-beta"
        rm -rf ./dist/.git
        .travis/release.sh "${env}-beta"
        echo "PUSHING ${env}-stable"
        rm -rf ./dist/.git
        .travis/release.sh "${env}-stable"
    done
fi

if [[ "${TRAVIS_BRANCH}" = "prod-beta" || "${TRAVIS_BRANCH}" = "prod-stable" ]]; then
    for env in beta stable
    do
        echo "PUSHING prod-${env}"
        rm -rf ./dist/.git
        .travis/release.sh "prod-${env}"
    done
fi
```

**Comment by omaciel** [comment]
Thanks @karelhala  for the suggestion. Would you have a few minutes to review it?

**Pull request closed without merging**
