### PR TITLE
change download action check

### PR DESCRIPTION
**Pull request by matoval**
change download action check

### CODE REVIEW

**Review by boaz0 — APPROVED** [review]

**Comment by boaz0** [comment]
@matoval - again Travis isn't running for you.

**Comment by boaz0** [comment]
You better run `npm run lint:js:fix`

**Comment by matoval** [comment]
> You better run `npm run lint:js:fix`

I run `npm run lint:js:fix` before every commit.

**Review by boaz0 — COMMENTED** [review]
LGTM :+1:

**Pull request merged**
