### PR TITLE
Feature general table

### PR DESCRIPTION
**Pull request by matoval**
General table to use for all our tables, already used for repo table and image table.

### CODE REVIEW

**Comment by omaciel** [comment]
@matoval how much test coverage will this have?

**Comment by omaciel** [comment]
Just saw the report from Codecov but for the changes themselves, how much coverage do we have?

**Comment by matoval** [comment]
> Just saw the report from Codecov but for the changes themselves, how much coverage do we have?

No tests were written for these files. I can write some now.

**Comment by omaciel** [comment]
> > Just saw the report from Codecov but for the changes themselves, how much coverage do we have?
> 
> No tests were written for these files. I can write some now.

It would give us a higher level of confidence when you "swap" the table component, I'd think :)

**Comment by matoval** [comment]
> > > Just saw the report from Codecov but for the changes themselves, how much coverage do we have?
> > 
> > 
> > No tests were written for these files. I can write some now.
> 
> It would give us a higher level of confidence when you "swap" the table component, I'd think :)

I like that idea! Adding tests now.

**Review by resoluteCoder — APPROVED** [review]
LGTM :+1: Merge when tests are ready :smile:

**Comment by adeliaferreira** [comment]
Lgtm 😊

**Pull request merged**
